alibaba/diagnose-tools

SOURCE/module/entry.c

commitid:0b48b10b0d8a5b修改后，返回值判断也需要相应修改。

commitid:0b48b10b0d8a5b need to modify the return value

---

SOURCE/module/Makefile

添加对3.10.0-1127.10.1.el7.x86_64编译支持

添加对3.10.0-1127.10.1.el7.x86_64编译支持

---

SOURCE/diagnose-tools/fs_shm.cc
SOURCE/diagnose-tools/irq_delay.cc
SOURCE/diagnose-tools/ping_delay.cc
SOURCE/diagnose-tools/rw_top.cc
SOURCE/diagnose-tools/tcp_retrans.cc
SOURCE/diagnose-tools/utilization.cc
SOURCE/module/fs/rw_top.c
SOURCE/module/fs/shm.c
SOURCE/module/net/ping_delay.c
SOURCE/module/net/tcp_retrans.c
SOURCE/uapi/fs_shm.h
SOURCE/uapi/ping_delay.h
SOURCE/uapi/rw_top.h
SOURCE/uapi/tcp_retrans.h

测试方法：
make; make test case=fs-shm

 kern: fs-shm: 将syscall接口修改为ioctl接口

---

SOURCE/diagnose-tools/fs_shm.cc
SOURCE/diagnose-tools/irq_delay.cc
SOURCE/diagnose-tools/ping_delay.cc
SOURCE/diagnose-tools/rw_top.cc
SOURCE/diagnose-tools/tcp_retrans.cc
SOURCE/diagnose-tools/utilization.cc
SOURCE/module/fs/rw_top.c
SOURCE/module/fs/shm.c
SOURCE/module/net/ping_delay.c
SOURCE/module/net/tcp_retrans.c
SOURCE/uapi/fs_shm.h
SOURCE/uapi/ping_delay.h
SOURCE/uapi/rw_top.h
SOURCE/uapi/tcp_retrans.h

kern: rw-top: 将syscall接口修改为ioctl接口

For baoyou

---

SOURCE/diagnose-tools/alloc_top.cc
SOURCE/diagnose-tools/drop_packet.cc
SOURCE/diagnose-tools/high_order.cc
SOURCE/module/mm/alloc_top.c
SOURCE/module/mm/high_order.c
SOURCE/module/net/drop_packet.c
SOURCE/uapi/alloc_top.h
SOURCE/uapi/drop_packet.h
SOURCE/uapi/high_order.h

测试方法：
make; make test case=drop-packet

 kern: drop-packet: 将syscall接口修改为ioctl接口

---

SOURCE/diagnose-tools/uprobe.cc
SOURCE/module/Makefile
SOURCE/module/kernel/mutex.c
SOURCE/module/kernel/uprobe.c
SOURCE/module/net/tcp_retrans.c
SOURCE/script/test.sh
SOURCE/uapi/uprobe.h

for-baoyou

---

SOURCE/diagnose-tools/internal.h
SOURCE/diagnose-tools/main.cc
SOURCE/diagnose-tools/net_bandwidth.cc
SOURCE/module/Makefile
SOURCE/module/chr_dev.c
SOURCE/module/entry.c
SOURCE/module/internal.h
SOURCE/module/net/net_bandwidth.c
SOURCE/module/net/net_entry.c
SOURCE/module/net/net_internal.h
SOURCE/module/stub.c
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/net_bandwidth.h

diagnose-tools net-bandwidth --activate
diagnose-tools net-bandwidth --report
效果和系统命令top差不多，实时打印每个连接的流量带宽

计算每个连接的实时流量带宽

---

SOURCE/diagnose-tools/net_bandwidth.cc
SOURCE/script/test.sh

可以使用 make test case=net-bandwidth 对reboot功能进行测试
同时修改net_bandwidth 工具使之兼容测试

添加net-bandwidth的测试用例

---

SOURCE/diagnose-tools/internal.h
SOURCE/diagnose-tools/main.cc
SOURCE/diagnose-tools/sig_info.cc
SOURCE/module/Makefile
SOURCE/module/chr_dev.c
SOURCE/module/entry.c
SOURCE/module/internal.h
SOURCE/module/kernel/kern_entry.c
SOURCE/module/kernel/kern_internal.h
SOURCE/module/kernel/sig_info.c
SOURCE/module/stub.c
SOURCE/script/test.sh
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/sig_info.h

diagnose-tools sig-info --activate
diagnose-tools sig-info --report='interval=2'
diagnose-tools sig-info --deactivate

添加sig-info功能,统计进程信号收发信息

---

.gitignore

Signed-off-by: Fanjun Kong <fanjun.kong@uisee.com>
Add .gitignore to make our workspace more clean.

diagnose-tools: Add .gitignore

---

SOURCE/diagnose-tools/exec_monitor.cc
SOURCE/diagnose-tools/sig_info.cc
SOURCE/module/internal.h
SOURCE/module/kernel/exec.c
SOURCE/module/kernel/sig_info.c
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/exec_monitor.h
SOURCE/uapi/sig_info.h

exec-monitor功能添加火焰图功能
完善sig-info，添加指定进程信号，打印调用链

exec-monitor功能添加火焰图功能 和 完善sig-info

---

Makefile
SOURCE/module/Makefile
SOURCE/module/fs/rw_top.c
SOURCE/module/fs/shm.c
SOURCE/module/internal.h
SOURCE/module/kernel/sys_delay.c
SOURCE/module/misc.c
SOURCE/module/mm/alloc_page.c

Signed-off-by: Fanjun Kong <fanjun.kong@uisee.com>
Acked-by: Baoyou Xie <baoyou.xie@alibaba-inc.com>
This patch fix build failed on aarch64 Ubuntu 16.04, kernel version 4.4.38.

fix build failed on aarch64 Ubuntu 16.04.

---

SOURCE/diagnose-tools/sig_info.cc
SOURCE/module/kernel/sig_info.c
SOURCE/uapi/sig_info.h

sig-info:支持只监控特定信号

---

SOURCE/module/pub/stack.c
SOURCE/module/symbol.c
SOURCE/module/symbol.h

Signed-off-by: Fanjun Kong <fanjun.kong@uisee.com>

kern: Add look up symbol: save_stack_trace_tsk

---

SOURCE/diagnose-tools/load.cc

Signed-off-by: Wang Long <w@laoqinren.net>

diagnose-tools: load-monitor: fix bug for diagnose-tools load-monitor --help

---

SOURCE/diagnose-tools/rw_top.cc
SOURCE/module/fs/rw_top.c
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/rw_top.h
documents/rw-top.md

支持传入 device 参数用于单独监控某个磁盘的读写。
Signed-off-by: weichenchen <weichen.chen@linux.alibaba.com>

rw-top: 添加 device 参数并在报告中展示磁盘信息

---

SOURCE/diagnose-tools/rw_top.cc
documents/rw-top.md

1）out: 支持raw-stack输出到指定文件
2）in: 支持单个解析1）输出的raw-stack文件
3）inlist: 支持raw-stack文件列表输入来解析多个raw-stack文件
4）console: 支持从控制台读取多个raw-stack文件列表，来解析多个raw-stack文件

rw-top:功能完善，包含：

---

Makefile

The compilation speed has been improved.
It is tested on an 8-core VM, and the compilation time is as follows:
before:
real    1m17.141s
user    1m7.063s
sys    0m8.087s
after:
real    0m23.920s
user    1m14.314s
sys    0m9.759s

Makefile: support parallel compilation

---

SOURCE/diagnose-tools/internal.h
SOURCE/diagnose-tools/main.cc
SOURCE/diagnose-tools/rw_sem.cc
SOURCE/module/Makefile
SOURCE/module/chr_dev.c
SOURCE/module/entry.c
SOURCE/module/internal.h
SOURCE/module/kernel/kern_entry.c
SOURCE/module/kernel/kern_internal.h
SOURCE/module/kernel/mutex.c
SOURCE/module/kernel/rw_sem.c
SOURCE/module/stub.c
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/mutex_monitor.h
SOURCE/uapi/rw_sem.h

Signed-off-by: fanjiyun <fanjiyun.fjy@alibaba-inc.com>

diagnose-tools: 将 rw-sem 功能从 mutex-monitor 中独立出来

---

SOURCE/diagnose-tools/mutex_monitor.cc
SOURCE/diagnose-tools/rw_sem.cc
SOURCE/module/kernel/mutex.c
SOURCE/module/kernel/rw_sem.c
SOURCE/script/test.sh
SOURCE/uapi/mutex_monitor.h
SOURCE/uapi/rw_sem.h

diagnose-tools: 
1) 修改 mutex-monitor 和 rw-sem 的阈值变量名；
2) 添加 rw-sem 测试用例
Signed-off-by: fanjiyun <fanjiyun.fjy@alibaba-inc.com>

diagnose-tools: 修改 mutex-monitor 和 rw-sem 的阈值变量名; 添加 rw-sem 测试用例

---

SOURCE/diagnose-tools/internal.h
SOURCE/diagnose-tools/main.cc
SOURCE/diagnose-tools/rss_monitor.cc
SOURCE/module/Makefile
SOURCE/module/chr_dev.c
SOURCE/module/entry.c
SOURCE/module/internal.h
SOURCE/module/mm/mm_entry.c
SOURCE/module/mm/mm_internal.h
SOURCE/module/mm/rss_monitor.c
SOURCE/module/stub.c
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/rss_monitor.h

Signed-off-by: fanjiyun <fanjiyun.fjy@alibaba-inc.com>

diagnose-tools: support rss-monitor

---

SOURCE/diagnose-tools/mm_leak.cc
SOURCE/module/mm/memory_leak.c
SOURCE/uapi/mm_leak.h

$ diagnose-tools mm-leak --help
mm-leak usage:
--help mm-leak help info
--activate
time-threshold default threshold(ms)
max-bytes max bytes recorded
min-bytes min bytes recorded
--deactivate
--verbose VERBOSE
--report dump log with text

mm-leak: add flags for --activate

---

SOURCE/diagnose-tools/internal.h
SOURCE/diagnose-tools/main.cc
SOURCE/diagnose-tools/net_bandwidth.cc
SOURCE/diagnose-tools/ping_delay6.cc
SOURCE/diagnose-tools/rw_top.cc
SOURCE/module/Makefile
SOURCE/module/chr_dev.c
SOURCE/module/entry.c
SOURCE/module/internal.h
SOURCE/module/net/net_entry.c
SOURCE/module/net/net_internal.h
SOURCE/module/net/ping_delay.c
SOURCE/module/net/ping_delay6.c
SOURCE/module/stub.c
SOURCE/uapi/ali_diagnose.h
SOURCE/uapi/ping_delay6.h

diagnose-tools:net 实现ping-delay6命令，支持IPv6地址

---

SOURCE/module/net/ping_delay.c
SOURCE/module/net/ping_delay6.c
SOURCE/script/test.sh
SOURCE/uapi/ping_delay.h
documents/ping-delay.md
documents/ping-delay6.md

该功能当前支持ALIOS_7U的常用版本（3.10 4.9 4.19）

diagnose-tools: net: ping_delay6支持4.19内核

---

SOURCE/module/pub/trace_point.c
SOURCE/module/symbol.c

Signed-off-by: CuiYunhui <623553547@qq.com>

added tracepoint can be hooked in module.
